spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pms?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
secret:
  key: Asjfwol2asf123142Ags1k23hnSA36as6f4qQ324FEsvb
auth:
  header:
    name: x-auth-token
token:
  expiration:
    time: 60